### ISSUE TITLE
pbs_server segmentation fault on HLE capable hardware with enabled lock-elision

### ISSUE THREAD

**Issue by wyldphyr3** [adaptivecomputing/torque#407]
**System:**
```
# uname -a
Linux melchior 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
```

```
# cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz
stepping	: 3
microcode	: 0x9e
cpu MHz		: 3406.490
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt
bogomips	: 6812.98
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

```
# dpkg -s libc6
Package: libc6
Status: install ok installed
Priority: required
Section: libs
Installed-Size: 10233
Maintainer: GNU Libc Maintainers <debian-glibc@lists.debian.org>
Architecture: amd64
Multi-Arch: same
Source: glibc
Version: 2.19-18+deb8u6
Replaces: libc6-amd64
Depends: libgcc1
Suggests: glibc-doc, debconf | debconf-2.0, locales
Breaks: hurd (<< 1:0.5.git20140203-1), libtirpc1 (<< 0.2.3), locales (<< 2.19), locales-all (<< 2.19), lsb-core (<= 3.2-27), nscd (<< 2.19)
Conflicts: prelink (<= 0.0.20090311-1), tzdata (<< 2007k-1), tzdata-etch
Conffiles:
 /etc/ld.so.conf.d/x86_64-linux-gnu.conf 593ad12389ab2b6f952e7ede67b8fbbf
```

```
# pbs_server --version
Version: 6.1.0
Commit: 1d115c5454b46ac0b4a6eb800665c7012bce6639
```

```
# ldd `which pbs_server`
	linux-vdso.so.1 (0x00007ffdac4a8000)
	libtorque.so.2 => /opt/shared-software/torque/lib/libtorque.so.2 (0x00007f25b5f1e000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f25b5d03000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f25b599c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f25b577f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f25b5577000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f25b526c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f25b4f6b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f25b4d55000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f25b49aa000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f25b47a6000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f25b4583000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f25b684b000)
```

**TORQUE installation via:**
```
./configure --prefix=/opt/shared-software/torque
make
sudo make install
```

**Environment:**
```
MANPATH=/opt/shared-software/purifyplus/releases/purify.i386_linux2.7.4.17/man:/opt/shared-software/intel/man:/usr/local/man:/usr/local/share/man:/usr/share/man
TERM=rxvt-256color
SHELL=/bin/bash
I_MPI_FABRICS=shm:tcp
USER=hkruse
MAIL=/var/mail/hkruse
PATH=/opt/shared-software/torque/bin:/opt/shared-software/torque/sbin:/opt/shared-software/purifyplus/releases/purify.i386_linux2.7.4.17:/opt/shared-software/intel/compilers_and_libraries/linux/mpi/intel64/bin:/opt/shared-software/intel/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
I_MPI_FALLBACK=1
PWD=/home/hkruse/software/torque-6.1.0/src/server
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/hkruse
LANGUAGE=en_US:en
LS_OPTIONS=--color=auto
LOGNAME=hkruse
I_MPI_ROOT=/opt/shared-software/intel/compilers_and_libraries/linux/mpi
OLDPWD=/home/hkruse/software/torque-6.1.0/src
_=/usr/bin/env
```

**Error:**
```
# pbs_server -D -d /var/spool/torque/
Segmentation fault
```

**Traceback:**
```
# gdb pbs_server 
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pbs_server...done.
(gdb) r -D -d /var/spool/
cron/    exim4/   mail/    rsyslog/ torque/  
(gdb) r -D -d /var/spool/torque/
Starting program: /opt/shared-software/torque/sbin/pbs_server -D -d /var/spool/torque/
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__lll_unlock_elision (lock=0x516f6a0, private=0)
    at ../nptl/sysdeps/unix/sysv/linux/x86/elision-unlock.c:29
29	../nptl/sysdeps/unix/sysv/linux/x86/elision-unlock.c: No such file or directory.
(gdb) backtrace 
#0  __lll_unlock_elision (lock=0x516f6a0, private=0)
    at ../nptl/sysdeps/unix/sysv/linux/x86/elision-unlock.c:29
#1  0x000000000049ca2d in unlock_ji_mutex (pjob=0x5163a30, 
    id=0x547ae0 <svr_enquejob(job*, int, char const*, bool, bool)::__func__> "svr_enquejob", 
    msg=0x5464c5 "1", logging=0) at svr_jobfunc.c:3993
#2  0x0000000000496320 in svr_enquejob (pjob=0x5163a30, has_sv_qs_mutex=1, prev_job_id=0x0, 
    have_reservation=false, being_recovered=true) at svr_jobfunc.c:423
#3  0x0000000000458b0c in pbsd_init_reque (pjob=0x5163a30, change_state=1) at pbsd_init.c:2821
#4  0x0000000000458135 in pbsd_init_job (pjob=0x5163a30, type=1) at pbsd_init.c:2557
#5  0x000000000045692d in handle_job_recovery (type=1) at pbsd_init.c:1796
#6  0x000000000045763b in handle_job_and_array_recovery (type=1) at pbsd_init.c:2100
#7  0x0000000000457cd5 in pbsd_init (type=1) at pbsd_init.c:2316
#8  0x000000000045e958 in main (argc=4, argv=0x7fffffffe4c8) at pbsd_main.c:1898
```

```
# valgrind --tool=helgrind pbs_server -D -d /var/spool/torque/
==26815== Helgrind, a thread error detector
==26815== Copyright (C) 2007-2013, and GNU GPL'd, by OpenWorks LLP et al.
==26815== Using Valgrind-3.10.0 and LibVEX; rerun with -h for copyright info
==26815== Command: pbs_server -D -d /var/spool/torque/
==26815== 
==26815== ---Thread-Announcement------------------------------------------
==26815== 
==26815== Thread #1 is the program's root thread
==26815== 
==26815== ----------------------------------------------------------------
==26815== 
==26815== Thread #1: lock order "0x823D9E0 before 0x823D970" violated
==26815== 
==26815== Observed (incorrect) order is: acquisition of lock at 0x823D970
==26815==    at 0x5D66616: pthread_mutex_lock (hg_intercepts.c:593)
==26815==    by 0x460163: lock_sv_qs_mutex(pthread_mutex_t*, char const*) (pbsd_main.c:3064)
==26815==    by 0x457CA4: pbsd_init(int) (pbsd_init.c:2311)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815==  followed by a later acquisition of lock at 0x823D9E0
==26815==    at 0x5D66616: pthread_mutex_lock (hg_intercepts.c:593)
==26815==    by 0x495952: get_svr_attr_b(int, bool*) (svr_func.c:546)
==26815==    by 0x455FB3: handle_array_recovery(int) (pbsd_init.c:1497)
==26815==    by 0x45762D: handle_job_and_array_recovery(int) (pbsd_init.c:2098)
==26815==    by 0x457CD4: pbsd_init(int) (pbsd_init.c:2316)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815== Required order was established by acquisition of lock at 0x823D9E0
==26815==    at 0x5D66616: pthread_mutex_lock (hg_intercepts.c:593)
==26815==    by 0x4557DA: setup_server_attrs(int) (pbsd_init.c:1006)
==26815==    by 0x457C3C: pbsd_init(int) (pbsd_init.c:2302)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815==  followed by a later acquisition of lock at 0x823D970
==26815==    at 0x5D66616: pthread_mutex_lock (hg_intercepts.c:593)
==26815==    by 0x460163: lock_sv_qs_mutex(pthread_mutex_t*, char const*) (pbsd_main.c:3064)
==26815==    by 0x4A2312: svr_recov_xml(char*, int) (svr_recov.c:347)
==26815==    by 0x45597C: setup_server_attrs(int) (pbsd_init.c:1067)
==26815==    by 0x457C3C: pbsd_init(int) (pbsd_init.c:2302)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815==  Lock at 0x823D9E0 was first observed
==26815==    at 0x5D6628A: pthread_mutex_init (hg_intercepts.c:518)
==26815==    by 0x45DF86: initialize_globals() (pbsd_main.c:1532)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Address 0x823d9e0 is 0 bytes inside a block of size 40 alloc'd
==26815==    at 0x5D62130: calloc (vg_replace_malloc.c:623)
==26815==    by 0x45DF2B: initialize_globals() (pbsd_main.c:1527)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Block was alloc'd by thread #1
==26815== 
==26815==  Lock at 0x823D970 was first observed
==26815==    at 0x5D6628A: pthread_mutex_init (hg_intercepts.c:518)
==26815==    by 0x45DF72: initialize_globals() (pbsd_main.c:1531)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Address 0x823d970 is 0 bytes inside a block of size 40 alloc'd
==26815==    at 0x5D62130: calloc (vg_replace_malloc.c:623)
==26815==    by 0x45DF15: initialize_globals() (pbsd_main.c:1526)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Block was alloc'd by thread #1
==26815== 
==26815== 
==26815== ----------------------------------------------------------------
==26815== 
==26815== Thread #1 unlocked a not-locked lock at 0x823DC70
==26815==    at 0x5D66AB6: pthread_mutex_unlock (hg_intercepts.c:707)
==26815==    by 0x4FA876: unlock_ss() (u_lock_ctl.c:178)
==26815==    by 0x438863: saveJobToXML(job*, char const*) (job_recov.c:1144)
==26815==    by 0x438B4E: job_save(job*, int, int) (job_recov.c:1264)
==26815==    by 0x43980D: job_recov(char const*) (job_recov.c:1812)
==26815==    by 0x456FAF: process_jobs_dirent(char const*) (pbsd_init.c:1952)
==26815==    by 0x45684B: handle_job_recovery(int) (pbsd_init.c:1779)
==26815==    by 0x45763A: handle_job_and_array_recovery(int) (pbsd_init.c:2100)
==26815==    by 0x457CD4: pbsd_init(int) (pbsd_init.c:2316)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815==  Lock at 0x823DC70 was first observed
==26815==    at 0x5D6628A: pthread_mutex_init (hg_intercepts.c:518)
==26815==    by 0x4FA600: lock_init() (u_lock_ctl.c:47)
==26815==    by 0x45DFB8: initialize_globals() (pbsd_main.c:1536)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Address 0x823dc70 is 0 bytes inside a block of size 40 alloc'd
==26815==    at 0x5D62130: calloc (vg_replace_malloc.c:623)
==26815==    by 0x4FA598: lock_init() (u_lock_ctl.c:41)
==26815==    by 0x45DFB8: initialize_globals() (pbsd_main.c:1536)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Block was alloc'd by thread #1
==26815== 
==26815== 
==26815== ----------------------------------------------------------------
==26815== 
==26815== Thread #1: lock order "0x823D9E0 before 0x823D970" violated
==26815== 
==26815== Observed (incorrect) order is: acquisition of lock at 0x823D970
==26815==    at 0x5D66616: pthread_mutex_lock (hg_intercepts.c:593)
==26815==    by 0x460163: lock_sv_qs_mutex(pthread_mutex_t*, char const*) (pbsd_main.c:3064)
==26815==    by 0x458AD8: pbsd_init_reque(job*, int) (pbsd_init.c:2817)
==26815==    by 0x458134: pbsd_init_job(job*, int) (pbsd_init.c:2557)
==26815==    by 0x45692C: handle_job_recovery(int) (pbsd_init.c:1796)
==26815==    by 0x45763A: handle_job_and_array_recovery(int) (pbsd_init.c:2100)
==26815==    by 0x457CD4: pbsd_init(int) (pbsd_init.c:2316)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815==  followed by a later acquisition of lock at 0x823D9E0
==26815==    at 0x5D66616: pthread_mutex_lock (hg_intercepts.c:593)
==26815==    by 0x49575D: is_svr_attr_set(int) (svr_func.c:461)
==26815==    by 0x4B0D0C: svr_find_job(char const*, int) (job_container.c:440)
==26815==    by 0x458A0D: check_jobs_queue(job*) (pbsd_init.c:2798)
==26815==    by 0x458AE7: pbsd_init_reque(job*, int) (pbsd_init.c:2819)
==26815==    by 0x458134: pbsd_init_job(job*, int) (pbsd_init.c:2557)
==26815==    by 0x45692C: handle_job_recovery(int) (pbsd_init.c:1796)
==26815==    by 0x45763A: handle_job_and_array_recovery(int) (pbsd_init.c:2100)
==26815==    by 0x457CD4: pbsd_init(int) (pbsd_init.c:2316)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815== Required order was established by acquisition of lock at 0x823D9E0
==26815==    at 0x5D66616: pthread_mutex_lock (hg_intercepts.c:593)
==26815==    by 0x4557DA: setup_server_attrs(int) (pbsd_init.c:1006)
==26815==    by 0x457C3C: pbsd_init(int) (pbsd_init.c:2302)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815==  followed by a later acquisition of lock at 0x823D970
==26815==    at 0x5D66616: pthread_mutex_lock (hg_intercepts.c:593)
==26815==    by 0x460163: lock_sv_qs_mutex(pthread_mutex_t*, char const*) (pbsd_main.c:3064)
==26815==    by 0x4A2312: svr_recov_xml(char*, int) (svr_recov.c:347)
==26815==    by 0x45597C: setup_server_attrs(int) (pbsd_init.c:1067)
==26815==    by 0x457C3C: pbsd_init(int) (pbsd_init.c:2302)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815==  Lock at 0x823D9E0 was first observed
==26815==    at 0x5D6628A: pthread_mutex_init (hg_intercepts.c:518)
==26815==    by 0x45DF86: initialize_globals() (pbsd_main.c:1532)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Address 0x823d9e0 is 0 bytes inside a block of size 40 alloc'd
==26815==    at 0x5D62130: calloc (vg_replace_malloc.c:623)
==26815==    by 0x45DF2B: initialize_globals() (pbsd_main.c:1527)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Block was alloc'd by thread #1
==26815== 
==26815==  Lock at 0x823D970 was first observed
==26815==    at 0x5D6628A: pthread_mutex_init (hg_intercepts.c:518)
==26815==    by 0x45DF72: initialize_globals() (pbsd_main.c:1531)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Address 0x823d970 is 0 bytes inside a block of size 40 alloc'd
==26815==    at 0x5D62130: calloc (vg_replace_malloc.c:623)
==26815==    by 0x45DF15: initialize_globals() (pbsd_main.c:1526)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Block was alloc'd by thread #1
==26815== 
==26815== 
==26815== ----------------------------------------------------------------
==26815== 
==26815== Thread #1: lock order "0x823D9E0 before 0x823D970" violated
==26815== 
==26815== Observed (incorrect) order is: acquisition of lock at 0x823D970
==26815==    at 0x5D66616: pthread_mutex_lock (hg_intercepts.c:593)
==26815==    by 0x460163: lock_sv_qs_mutex(pthread_mutex_t*, char const*) (pbsd_main.c:3064)
==26815==    by 0x458AD8: pbsd_init_reque(job*, int) (pbsd_init.c:2817)
==26815==    by 0x458134: pbsd_init_job(job*, int) (pbsd_init.c:2557)
==26815==    by 0x45692C: handle_job_recovery(int) (pbsd_init.c:1796)
==26815==    by 0x45763A: handle_job_and_array_recovery(int) (pbsd_init.c:2100)
==26815==    by 0x457CD4: pbsd_init(int) (pbsd_init.c:2316)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815==  followed by a later acquisition of lock at 0x823D9E0
==26815==    at 0x5D66616: pthread_mutex_lock (hg_intercepts.c:593)
==26815==    by 0x49575D: is_svr_attr_set(int) (svr_func.c:461)
==26815==    by 0x4B0D1A: svr_find_job(char const*, int) (job_container.c:441)
==26815==    by 0x458A0D: check_jobs_queue(job*) (pbsd_init.c:2798)
==26815==    by 0x458AE7: pbsd_init_reque(job*, int) (pbsd_init.c:2819)
==26815==    by 0x458134: pbsd_init_job(job*, int) (pbsd_init.c:2557)
==26815==    by 0x45692C: handle_job_recovery(int) (pbsd_init.c:1796)
==26815==    by 0x45763A: handle_job_and_array_recovery(int) (pbsd_init.c:2100)
==26815==    by 0x457CD4: pbsd_init(int) (pbsd_init.c:2316)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815== Required order was established by acquisition of lock at 0x823D9E0
==26815==    at 0x5D66616: pthread_mutex_lock (hg_intercepts.c:593)
==26815==    by 0x4557DA: setup_server_attrs(int) (pbsd_init.c:1006)
==26815==    by 0x457C3C: pbsd_init(int) (pbsd_init.c:2302)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815==  followed by a later acquisition of lock at 0x823D970
==26815==    at 0x5D66616: pthread_mutex_lock (hg_intercepts.c:593)
==26815==    by 0x460163: lock_sv_qs_mutex(pthread_mutex_t*, char const*) (pbsd_main.c:3064)
==26815==    by 0x4A2312: svr_recov_xml(char*, int) (svr_recov.c:347)
==26815==    by 0x45597C: setup_server_attrs(int) (pbsd_init.c:1067)
==26815==    by 0x457C3C: pbsd_init(int) (pbsd_init.c:2302)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815==  Lock at 0x823D9E0 was first observed
==26815==    at 0x5D6628A: pthread_mutex_init (hg_intercepts.c:518)
==26815==    by 0x45DF86: initialize_globals() (pbsd_main.c:1532)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Address 0x823d9e0 is 0 bytes inside a block of size 40 alloc'd
==26815==    at 0x5D62130: calloc (vg_replace_malloc.c:623)
==26815==    by 0x45DF2B: initialize_globals() (pbsd_main.c:1527)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Block was alloc'd by thread #1
==26815== 
==26815==  Lock at 0x823D970 was first observed
==26815==    at 0x5D6628A: pthread_mutex_init (hg_intercepts.c:518)
==26815==    by 0x45DF72: initialize_globals() (pbsd_main.c:1531)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Address 0x823d970 is 0 bytes inside a block of size 40 alloc'd
==26815==    at 0x5D62130: calloc (vg_replace_malloc.c:623)
==26815==    by 0x45DF15: initialize_globals() (pbsd_main.c:1526)
==26815==    by 0x45E1EF: main (pbsd_main.c:1642)
==26815==  Block was alloc'd by thread #1
==26815== 
==26815== 
==26815== ----------------------------------------------------------------
==26815== 
==26815== Thread #1 unlocked a not-locked lock at 0x8274C60
==26815==    at 0x5D66AB6: pthread_mutex_unlock (hg_intercepts.c:707)
==26815==    by 0x49CA2C: unlock_ji_mutex(job*, char const*, char const*, int) (svr_jobfunc.c:3993)
==26815==    by 0x49631F: svr_enquejob(job*, int, char const*, bool, bool) (svr_jobfunc.c:423)
==26815==    by 0x458B0B: pbsd_init_reque(job*, int) (pbsd_init.c:2821)
==26815==    by 0x458134: pbsd_init_job(job*, int) (pbsd_init.c:2557)
==26815==    by 0x45692C: handle_job_recovery(int) (pbsd_init.c:1796)
==26815==    by 0x45763A: handle_job_and_array_recovery(int) (pbsd_init.c:2100)
==26815==    by 0x457CD4: pbsd_init(int) (pbsd_init.c:2316)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815==  Lock at 0x8274C60 was first observed
==26815==    at 0x5D6628A: pthread_mutex_init (hg_intercepts.c:518)
==26815==    by 0x4D1BF1: job::job() (job.cpp:24)
==26815==    by 0x432EFE: job_alloc() (job_func.c:759)
==26815==    by 0x439700: job_recov(char const*) (job_recov.c:1762)
==26815==    by 0x456FAF: process_jobs_dirent(char const*) (pbsd_init.c:1952)
==26815==    by 0x45684B: handle_job_recovery(int) (pbsd_init.c:1779)
==26815==    by 0x45763A: handle_job_and_array_recovery(int) (pbsd_init.c:2100)
==26815==    by 0x457CD4: pbsd_init(int) (pbsd_init.c:2316)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815==  Address 0x8274c60 is 0 bytes inside a block of size 40 alloc'd
==26815==    at 0x5D62130: calloc (vg_replace_malloc.c:623)
==26815==    by 0x4D1BCB: job::job() (job.cpp:23)
==26815==    by 0x432EFE: job_alloc() (job_func.c:759)
==26815==    by 0x439700: job_recov(char const*) (job_recov.c:1762)
==26815==    by 0x456FAF: process_jobs_dirent(char const*) (pbsd_init.c:1952)
==26815==    by 0x45684B: handle_job_recovery(int) (pbsd_init.c:1779)
==26815==    by 0x45763A: handle_job_and_array_recovery(int) (pbsd_init.c:2100)
==26815==    by 0x457CD4: pbsd_init(int) (pbsd_init.c:2316)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815==  Block was alloc'd by thread #1
==26815== 
==26815== 
==26815== 
==26815== Process terminating with default action of signal 11 (SIGSEGV)
==26815==  General Protection Fault
==26815==    at 0x6E312CB: __lll_unlock_elision (elision-unlock.c:33)
==26815==    by 0x5D66B18: pthread_mutex_unlock (hg_intercepts.c:710)
==26815==    by 0x49CA2C: unlock_ji_mutex(job*, char const*, char const*, int) (svr_jobfunc.c:3993)
==26815==    by 0x49631F: svr_enquejob(job*, int, char const*, bool, bool) (svr_jobfunc.c:423)
==26815==    by 0x458B0B: pbsd_init_reque(job*, int) (pbsd_init.c:2821)
==26815==    by 0x458134: pbsd_init_job(job*, int) (pbsd_init.c:2557)
==26815==    by 0x45692C: handle_job_recovery(int) (pbsd_init.c:1796)
==26815==    by 0x45763A: handle_job_and_array_recovery(int) (pbsd_init.c:2100)
==26815==    by 0x457CD4: pbsd_init(int) (pbsd_init.c:2316)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== ----------------------------------------------------------------
==26815== 
==26815== Thread #1: Exiting thread still holds 1 lock
==26815==    at 0x6E312CB: __lll_unlock_elision (elision-unlock.c:33)
==26815==    by 0x5D66B18: pthread_mutex_unlock (hg_intercepts.c:710)
==26815==    by 0x49CA2C: unlock_ji_mutex(job*, char const*, char const*, int) (svr_jobfunc.c:3993)
==26815==    by 0x49631F: svr_enquejob(job*, int, char const*, bool, bool) (svr_jobfunc.c:423)
==26815==    by 0x458B0B: pbsd_init_reque(job*, int) (pbsd_init.c:2821)
==26815==    by 0x458134: pbsd_init_job(job*, int) (pbsd_init.c:2557)
==26815==    by 0x45692C: handle_job_recovery(int) (pbsd_init.c:1796)
==26815==    by 0x45763A: handle_job_and_array_recovery(int) (pbsd_init.c:2100)
==26815==    by 0x457CD4: pbsd_init(int) (pbsd_init.c:2316)
==26815==    by 0x45E957: main (pbsd_main.c:1898)
==26815== 
==26815== 
==26815== For counts of detected and suppressed errors, rerun with: -v
==26815== Use --history-level=approx or =none to gain increased speed, at
==26815== the cost of reduced accuracy of conflicting-access information
==26815== ERROR SUMMARY: 7 errors from 6 contexts (suppressed: 0 from 0)
Segmentation fault
```

**Some guessing:**
Debian enables lock elision in libc by default. On HLE enabled CPUs ```pthread_mutex_unlock``` is handled through ```__lll_unlock_elision```. This low level unlocking function does not accept unlocking of free mutexes. From what I've read so far, other unlocking functions seemed to accept that.

Line 29 of ```elision_unlock.c``` in libc sources has a comment:
```
26  /* When the lock was free we're in a transaction.
27     When you crash here you unlocked a free lock.  */
28  if (*lock == 0)
29    _xend();
```

**Comment by dbeer** [comment]
This was fixed with commit 8ab26691bbdd82e19e103b1650e16664d9229360
